### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by GregoryTravis** [isislovecruft/patternsinthevoid#6]
These links seem to be broken -- have the files moved?

**Comment by isislovecruft** [comment]
@GregoryTravis Hi! Which links?

**Comment by GregoryTravis** [comment]
Oh, sorry.  I don't remember now exactly, it was pdf chapters of a book on
Quantum Mechanics.  I just tried to find it again and the 'library' repo
has a takedown notice.  It might have been in there.

**Comment by isislovecruft** [comment]
The library repo has moved to https://github.com/isislovecruft/library-- because some guy from Stanford falsely¹ claimed to have copyright on my copy of Feynman's Lectures.

¹ He actually has copyright over his preface to a different edition, but he's become famous for threatening to sue people right and left over stuff he doesn't own.
